### ISSUE TITLE
text color for dark mode 

### ISSUE THREAD

**Issue by Roni750** [hasadna/open-bus-map-search#357]
On some pages the text-colors were still replaced to contrast the dark background.
I believe this happens on many pages, one example is the /gaps page:

![image](https://github.com/hasadna/open-bus-map-search/assets/104915367/7f0a7a23-a923-4e98-b01c-3878deaff394)

![image](https://github.com/hasadna/open-bus-map-search/assets/104915367/785a4106-0aa1-4e8d-bc36-5cf7888e9423)

Notice this isn't true just for mobile, but for all breakpoints as well.

**Comment by Roni750** [comment]
Alright then, I'll handle this one :)

**Comment by shootermv** [comment]
i think  (as result of solving some other issue) - this page currently has no more `side labels`

**Comment by oribro** [comment]
@Roni750 What is the requirement for text color in dark mode? Should it always be white? 
If so, I have no problem trying to fix this, otherwise can you please state the expected behaviour?

**Comment by Roni750** [comment]
First of all sorry for the delay with handling this issue. I had a lot on my plate lately..
@oribro Hey mate, from what I've seen the color that's already in use for dark mode is 0.85 opacity pure white, which is: rgba(255, 255, 255, 0.85), I believe this would be a great fit for the rest of the website.

**Comment by oribro** [comment]
NP, I think I know how to do this 🥇

**Comment by oribro** [comment]
@Roni750 I've investigated further and could use some help. 
Turns out that a part of the problem is rooted in the _**placeholders**_ color while the text color stays white, as this picture shows:
![image](https://github.com/hasadna/open-bus-map-search/assets/22520147/9772d243-4b93-4138-b544-40f88ada1275)
One solution I think of is to change every selector's placeholder color to white, or is there only one global place to change all selectors?
Once we deal with this there is another problem as this picture shows: (there should be text in the marked area but it's of color grey by default for some reason)
![image](https://github.com/hasadna/open-bus-map-search/assets/22520147/e21b29d6-b7c9-4825-b14a-5f9851879856)
So first I think we need to figure the scope of the issue and where the problem occurs.

Any thoughts?

**Comment by NoamGaash** [comment]
I think that the easiest approach will be adding:
```js
  const { isDarkTheme, toggleTheme } = useTheme()
```
and 
```jsx
className={cn('component-name', { dark: isDarkTheme })}
```
wherever it's needed, and use CSS selectors to color each place individually.

**Comment by YuvalMasada** [comment]
hi all,
The Reason the text disappears when you change mode is because you didn't use the MaterialUI Label.
In order for the Theme to work for the label you have to use the <InputLabel> Component from MaterialUI.
I did the following change and it worked for me:

1. Switch one of the labels  from **<Label text={t('choose_line')} />** to **<InputLabel>{t('choose_line')}</InputLabel>**.
2. Add the missing import for the InputLabel.
3. test Dark mode.
I don't know if there are any side effects to this fix since i don't know the code or product too much, but it might be an easier solution.
hope my message was clear :)

**Comment by NoamGaash** [comment]
@YuvalMasada that's sound amazing. Please feel free to submit a PR with your suggestions

**Comment by YuvalMasada** [comment]
@NoamGaash I would gladly give it a try and submit , but from what i see in production it seems to be working fine.
this is Production  -> https://open-bus-map-search.hasadna.org.il/  ?
Anyway i would be happy to work on other PRs.

**Comment by NoamGaash** [comment]
@YuvalMasada Yup, that's the production. You're right, looks like someone already solved it :tada: 
@Roni750 Did we miss something? Please re-open if necessary
@YuvalMasada Any contribution will be appreciated
