### ISSUE TITLE
Can't put 17א where I'm advised to put 17א

### ISSUE THREAD

**Issue by i5x64BIT** [hasadna/open-bus-map-search#520]
<img width="412" alt="Screenshot 2024-02-23 at 19 23 43" src="https://github.com/hasadna/open-bus-map-search/assets/62185136/c1ded1c7-89d2-46e8-9902-7f2650c74c7f">

דפוסי נסיאות שלא יצאו -> מספר קו
Probably can be fixed by changing the input type, check if api can recieve text values.
Try to add autocomplete

**Comment by davis0011** [comment]
I know where to change the input type.
I checked and the api can recieve a text value, it gets lineNumber(route_short_name) as a string.
@NoamGaash Can I be assigned to this issue?

Regarding the autocomplete, I didn't come up with an idea because the API gives back results for the exact lineNumber you provide, and iterating through the entire result to get all lineNumbers of a spesific operator (without a specific lineNumber) will take a long time because there are a lot of results.
